### ISSUE TITLE
wallet.sh heavy CPU useage when doing txs

### ISSUE THREAD

**Issue by bfish10** [harmony-one/pangaea-community#36]
using node.sh binary - harmony, version v4662-pangaea-20190920.0-0-gc2324c41 
using wallet.sh binary - wallet, version v4662-pangaea-20190920.0-0-gc2324c41

CPU useage can rise from 30% to 70%+ from a single transaction. Using 2 CPU, 4 GB ram.
e.g.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
28441 root      20   0  763760  29500  23864 R  72.1  0.7   0:02.99 wallet      
28422 root      20   0 3414356 317060  26896 S  42.2  7.8   0:04.85 wallet      
 1154 root      20   0 3781312 315688  28760 S  29.9  7.8 190:04.37 harmony     
28458 root      20   0  757344  22504  19032 R  18.9  0.6   0:00.57 wallet

**Comment by harmony-ek** [comment]
Harmony eng team has independently discovered this issue and fixed it.  It will be part of the new release we are about to rebootstrap the network with.  Once done, we will post an announcement in the channels; please do `./wallet.sh -t -d` to upgrade to the new binary after the announcement.
