### ISSUE TITLE
Panic: not aquiring lock on DHT file: Stopped node from running

### ISSUE THREAD

**Issue by bfish10** [harmony-one/pangaea-community#44]
Using: 
Build: Harmony (C) 2019. harmony, version v4696-pangaea-20190924.0-0-ge3030c50 (jenkins@ 2019-09-25T01:31:41+0000).
Build: Harmony (C) 2019. wallet, version v4662-pangaea-20190920.0-0-gc2324c41 (jenkins@ 2019-09-21T06:31:36+0000).
Panic alert stopped node from running.
goroutine 1 [running]:
github.com/harmony-one/harmony/api/service/networkinfo.New(0x14bc220, 0xc0001f4d80, 0x113aa42, 0x19, 0x0, 0x0, 0x0, 0x0, 0x10c7e80)
	/mnt/jenkins/workspace/harmony-release/harmony/api/service/networkinfo/service.go:66 +0x503
github.com/harmony-one/harmony/node.(*Node).setupForClientNode(0xc000826400)
	/mnt/jenkins/workspace/harmony-release/harmony/node/service_setup.go:63 +0x70
github.com/harmony-one/harmony/node.(*Node).ServiceManagerSetup(0xc000826400)
	/mnt/jenkins/workspace/harmony-release/harmony/node/service_setup.go:86 +0xc6
main.createWalletNode(0xc000401f20)
	/mnt/jenkins/workspace/harmony-release/harmony/cmd/client/wallet/main.go:309 +0x2b4
main.processTransferCommand()
	/mnt/jenkins/workspace/harmony-release/harmony/cmd/client/wallet/main.go:729 +0x61a
main.main()
	/mnt/jenkins/workspace/harmony-release/harmony/cmd/client/wallet/main.go:247 +0x55f
![Screenshot from 2019-09-24 20-52-52](https://user-images.githubusercontent.com/54595487/65568483-d950d400-df0e-11e9-8166-1581b44ca59e.png)

**Comment by chainum** [comment]
Fixed in master by https://github.com/harmony-one/harmony/commit/2240b8d48f5ce5cd72cbdb82b6b7f49d78a2a9df#diff-555d4004df49f95cb0ff4e944b9b9365
