### ISSUE TITLE
Transfers from-to no existence shards produces a run-time error.

### ISSUE THREAD

**Issue by kenny-gordon** [harmony-one/pangaea-community#47]
Expected outcome was an error response explaining that shards ID's are incorrectly entered.
 
```
./wallet.sh -t transfer --from one1v6vflk65tzpdlf8p5ntpeglv3tf2d20q96k3cj --to one196vgv5zjlhv5s25hhyjfy86hg3fg5ws4pug00u --shardID 4 --toShardID 4 --amount 0.018442 --pass pass:
Using pangaea profile for wallet
panic: runtime error: index out of range

goroutine 1 [running]:
main.processTransferCommand()
        /mnt/jenkins/workspace/harmony-release/harmony/cmd/client/wallet/main.go:716 +0x13bb
main.main()
        /mnt/jenkins/workspace/harmony-release/harmony/cmd/client/wallet/main.go:247 +0x55f
```

**Comment by kenny-gordon** [comment]
Transfers to no existence shards doesn't produce an error but will generate a Transaction Id

```
sudo ./wallet.sh -t transfer --from one1v6vflk65tzpdlf8p5ntpeglv3tf2d20q96k3cj --to one196vgv5zjlhv5s25hhyjfy86hg3fg5ws4pug00u --shardID 2 --toShardID 4 --amount 0.018442 --pass pass:
Using pangaea profile for wallet
Unlock account succeeded! 'pass:'
Transaction Id for shard 2: 0xac3fda1f7a71238d3323a0314c457c164c0473cd30f6ca316c2643bf28829d56
```

**Comment by kenny-gordon** [comment]
The error still persists with newer wallet versions

`LD_LIBRARY_PATH=. ./wallet -version
Harmony (C) 2019. wallet, version v4704-v1-20190924.0-0-g252aa562 (jenkins@ 2019-09-25T00:05:28+0000)
LD_LIBRARY_PATH=. ./harmony -version
Harmony (C) 2019. harmony, version v4696-pangaea-20190924.0-0-ge3030c50 (jenkins@ 2019-09-25T01:31:41+0000)
sudo ./wallet.sh -t transfer --from one1v6vflk65tzpdlf8p5ntpeglv3tf2d20q96k3cj --to one1v6vflk65tzpdlf8p5ntpeglv3tf2d20q96k3cj --amount 1000 --shardID 4 --toShardID 4 --pass pass:
Using pangaea profile for wallet
panic: runtime error: index out of range

goroutine 1 [running]:
main.processTransferCommand()
        /mnt/jenkins/workspace/harmony-release/harmony/cmd/client/wallet/main.go:716 +0x13bb
main.main()
        /mnt/jenkins/workspace/harmony-release/harmony/cmd/client/wallet/main.go:247 +0x55f
`

**Comment by chainum** [comment]
Fixed and merged in harmony & go-sdk:

https://github.com/harmony-one/harmony/pull/1702
https://github.com/harmony-one/go-sdk/pull/29
