### ISSUE TITLE
transfer is complaining about shard id, even though shard id is provided

### ISSUE THREAD

**Issue by satishkumarj** [harmony-one/pangaea-community#50]
transfer is complaining about shard id, even though shard id is provided

`root@JSKPangaeaNode:~# ./wallet.sh -t transfer --to one1yvxwzsj7gh36774puwtw9tgfg58cfz3gkr7cfk --from one18ndk75w6nea5x7nxjhvv0xj6zfdsc7nks3f778 --amount 1.0 --shardID 0  --pass pass:
Using pangaea profile for wallet
Please specify the shard ID for the transfer (e.g. --shardID=0)
root@JSKPangaeaNode:~# date
Thu 26 Sep 2019 04:04:45 PM UTC
root@JSKPangaeaNode:~# LD_LIBRARY_PATH=$(pwd) ./harmony -version                                                                                
Harmony (C) 2019. harmony, version v4696-pangaea-20190924.0-0-ge3030c50 (jenkins@ 2019-09-25T01:31:41+0000)`

**Comment by satishkumarj** [comment]
transfer is complaining about shard id, even though shard id is provided

`root@JSKPangaeaNode:~# ./wallet.sh -t transfer --to one1yvxwzsj7gh36774puwtw9tgfg58cfz3gkr7cfk --from one18ndk75w6nea5x7nxjhvv0xj6zfdsc7nks3f778 --amount 1.0 --shardID 0  --pass pass:
Using pangaea profile for wallet
Please specify the shard ID for the transfer (e.g. --shardID=0)
root@JSKPangaeaNode:~# date
Thu 26 Sep 2019 04:04:45 PM UTC
root@JSKPangaeaNode:~# LD_LIBRARY_PATH=$(pwd) ./harmony -version                                                                                Harmony (C) 2019. harmony, version v4696-pangaea-20190924.0-0-ge3030c50 (jenkins@ 2019-09-25T01:31:41+0000)

`

**Comment by developery-nl** [comment]
you specified the shard id from where coins must be transfered from --shardID , but you also need to provide --toShardID to specify the destination shard

**Comment by satishkumarj** [comment]
it works, however it would be intuitive to say, "Provide to Shard Id"

thanks anyway.
